import os,sys,codecs

print 'reading all lines'
sens=codecs.open(sys.argv[1],'r').read().strip().split('\n\n')

s0b0_writer=codecs.open(sys.argv[2]+'.s0b0.txt','w')
sw0bw0_writer=codecs.open(sys.argv[2]+'.sw0bw0.txt','w')
s0bw0_writer=codecs.open(sys.argv[2]+'.s0bw0.txt','w')
sw0b0_writer=codecs.open(sys.argv[2]+'.sw0b0.txt','w')
s0b1_writer=codecs.open(sys.argv[2]+'.s0b1.txt','w')
s0b2_writer=codecs.open(sys.argv[2]+'.s0b2.txt','w')
s0b0b1_writer=codecs.open(sys.argv[2]+'.s0b0b1.txt','w')
s0b1b2_writer=codecs.open(sys.argv[2]+'.s0b1b2.txt','w')
s0hs0b0_writer=codecs.open(sys.argv[2]+'.s0hs0b0.txt','w')
b0b1_writer=codecs.open(sys.argv[2]+'.b0b1.txt','w')
b0b2_writer=codecs.open(sys.argv[2]+'.b0b2.txt','w')
b0b1b2_writer=codecs.open(sys.argv[2]+'.b0b1b2.txt','w')
s0sl0b0_writer=codecs.open(sys.argv[2]+'.s0sl0b0.txt','w')
s0sr0b0_writer=codecs.open(sys.argv[2]+'.s0sr0b0.txt','w')
s0b0bl0_writer=codecs.open(sys.argv[2]+'.s0b0bl0.txt','w')

count=0
for sen in sens:
	ls=sen.strip().split('\n')
	s0b0_output=list()
	sw0bw0_output=list()
	sw0b0_output=list()
	s0bw0_output=list()
	s0b1_output=list()
	s0b2_output=list()
	s0b0b1_output=list()
	s0b1b2_output=list()
	s0hs0b0_output=list()
	b0b1_output=list()
	b0b2_output=list()
	b0b1b2_output=list()
	s0sl0b0_output=list()
	s0sr0b0_output=list()
	s0b0bl0_output=list()
	for l in ls:
		spl=l.split('\t')
		s0b0_output.append(spl[1]+'&'+spl[3])
		sw0bw0_output.append(spl[0]+'&'+spl[2])
		sw0b0_output.append(spl[0]+'&'+spl[3])
		s0bw0_output.append(spl[1]+'&'+spl[2])
		s0b1_output.append(spl[1]+'&'+spl[5])
		s0b2_output.append(spl[1]+'&'+spl[7])
		s0b0b1_output.append(spl[1]+'&'+spl[3]+'&'+spl[5])
		s0b1b2_output.append(spl[1]+'&'+spl[5]+'&'+spl[7])
		s0hs0b0_output.append(spl[10]+'&'+spl[1]+'&'+spl[3])
		b0b1_output.append(spl[3]+'&'+spl[5])
		b0b2_output.append(spl[3]+'&'+spl[7])
		b0b1b2_output.append(spl[3]+'&'+spl[5]+'&'+spl[7])
		s0sl0b0_output.append(spl[1]+'&'+spl[8]+'&'+spl[3])
		s0sr0b0_output.append(spl[1]+'&'+spl[9]+'&'+spl[3])
		s0b0bl0_output.append(spl[1]+'&'+spl[3]+'&'+spl[11])

	s0b0_writer.write(' '.join(s0b0_output)+'\n')
	sw0bw0_writer.write(' '.join(sw0bw0_output)+'\n')
	s0bw0_writer.write(' '.join(s0bw0_output)+'\n')
	sw0b0_writer.write(' '.join(sw0b0_output)+'\n')
	s0b1_writer.write(' '.join(s0b1_output)+'\n')
	s0b2_writer.write(' '.join(s0b2_output)+'\n')
	s0b0b1_writer.write(' '.join(s0b0b1_output)+'\n')
	s0b1b2_writer.write(' '.join(s0b1b2_output)+'\n')
	s0hs0b0_writer.write(' '.join(s0hs0b0_output)+'\n')
	b0b1_writer.write(' '.join(b0b1_output)+'\n')
	b0b2_writer.write(' '.join(b0b2_output)+'\n')
	b0b1b2_writer.write(' '.join(b0b1b2_output)+'\n')

	s0sl0b0_writer.write(' '.join(s0sl0b0_output)+'\n')
	s0sr0b0_writer.write(' '.join(s0sr0b0_output)+'\n')
	s0b0bl0_writer.write(' '.join(s0b0bl0_output)+'\n')

	count+=1
	if count%100000==0:
		sys.stdout.write(str(count)+'...')

s0b0_writer.close()
sw0bw0_writer.close()
s0bw0_writer.close()
sw0b0_writer.close()
s0b1_writer.close()
s0b2_writer.close()
s0b0b1_writer.close()
s0b1b2_writer.close()
s0hs0b0_writer.close()
b0b1_writer.close()
b0b1b2_writer.close()
b0b2_writer.close()
s0sl0b0_writer.close()
s0sr0b0_writer.close()
s0b0bl0_writer.close()

sys.stdout.write(str(count)+'\n')